### ISSUE TITLE
Update contributing with Maven wrappers

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf#19]
The goal of this issue is to update the Contributing.md file to explain why we provide Maven wrappers and how to use them.

**Comment by myluco** [comment]
I could work on this. I would need some more info.

**Comment by jeanbisutti** [comment]
@myluco Great!

The idea is to explain in the Build section of contributing that we need a given JDK and we need a MAaen 3 version. If the user don't want to install Maven 3 then he can use Maven wrappers, and we could explain how to use the wrappers on Windows, Linux and Mac.

Documentation on Maven wrapper: https://github.com/takari/maven-wrapper, https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc

**Comment by jeanbisutti** [comment]
@myluco Would you like to work on this?

**Comment by artyonline** [comment]
I haven't worked with Maven, but I would like to give it a shot. Can I try?

**Comment by jeanbisutti** [comment]
@artyonline Yes! You can work on this and so test Maven!

**Comment by jeanbisutti** [comment]
Hi @artyonline,
Are you always interested in working on this Issue?

**Comment by artyonline** [comment]
No I couldn't get around to it.

**Comment by rdm100** [comment]
Hi,

Has this documentation been fixed yet?

**Comment by jeanbisutti** [comment]
Hi @rdm100,

This documentation issue is not fixed.

**Comment by rdm100** [comment]
So, should it be adding more detail to this "The idea is to explain in the Build section of contributing that we need a given JDK and we need a MAaen 3 version. If the user does not want to install Maven 3 then he can use Maven wrappers, and we could explain how to use the wrapper on Windows, Linux and Mac."

in this section 

"Building from Source

Spring Boot source can be built from the command line using Apache Maven on JDK 1.8 or above. We include ‘Maven Wrapper’ scripts (./mvnw or mvnw.bat) that you can run rather than needing to install Maven locally."

it already says the specific JDK needed in the section pasted directly above, 1.8 yeah?

Is adding the detail of "explain how to use the wrapper on Windows, Linux and Mac" the main detail to be added?

Just checking everything as it would be my first time contributing, so sorry for any stupid questions.

**Comment by jeanbisutti** [comment]
You are welcome @rdm100. 
Perhaps we could underly in [contributing](https://github.com/quick-perf/quickperf/blob/master/CONTRIBUTING.md#build-quickperf) that we need `JDK (OpenJDK, ...) >= 11 or Oracle JDK >= 1.8`.
After that, we could explain that it is possible to build with Maven installed in the machine or by using Maven wrappers. 
I confirm that "explain how to use the wrapper on Windows, Linux and Mac" is the main point. I think that it would be usefull to write in contributing the command lines allowing to build QuickPerf with Maven wrapper. Don't hesitate to submit a PR to discuss from a first version. Don't hesitate if you have questions @rdm100.

**Comment by rdm100** [comment]
Hi,

The section below from the "Building From Source" section

"Spring Boot source can be built from the command line using Apache Maven on JDK 1.8 or above. We include ‘Maven Wrapper’ scripts (./mvnw or mvnw.bat) that you can run rather than needing to install Maven locally."

has changed to the text below

"Spring Boot source can be built from the command line using Gradle on JDK 1.8 or above. We include Gradle’s wrapper scripts (./gradlew or gradlew.bat) that you can run rather than needing to install Gradle locally."

So, I am a bit confused about where I should include the information on the "Maven Wrapper" as this section seems to be about Gradle now?

Or is this just some separate information on Gradle that has been added in and I have to add in the information about the "Maven Wrapper" with Windows, Linux and Mac etc after the information on Gradle?

Cheers

**Comment by rdm100** [comment]
I submitted a pull request let me know if that is in the right direction.

**Comment by spencergibb** [comment]
A PR to spring boot (which no longer uses maven) doesn't make much sense.

**Comment by jeanbisutti** [comment]
@rdm100 The [QuickPerf contributing file](https://github.com/quick-perf/quickperf/blob/master/CONTRIBUTING.md) has to be updated in the frame of this issue.

**Comment by rdm100** [comment]
@spencergibb  was it only recently that Spring Boot stopped using Maven because the CONTRIBUTING.adoc include info about Maven till 3 days ago?

@jeanbisutti not sure what you mean from your last comment I thought the file I was meant to update was the CONTRIBUTING.adoc file at https://github.com/spring-projects/spring-boot

When you said 
"I think that it would be usefull to write in contributing the command lines allowing to build QuickPerf with Maven wrapper."

Did you mean to update the QuickPerf contributing file?

Sorry all for any misunderstanding.

**Comment by jeanbisutti** [comment]
@rdm100 I meant QuickPerf contributing file. No problem for the misunderstanding.

**Comment by rdm100** [comment]
@jeanbisutti does the info on how to build with Maven wrapper on Linux, Mac and Windows need to be added to the QuickPerf contributing file? 

So I would add that you use the mvn -N io.takari:maven:0.7.7:wrapper command and then ./mvnw clean install, but with more details to the QuickPerf contributing file?

**Comment by jeanbisutti** [comment]
@rdm100 
> does the info on how to build with Maven wrapper on Linux, Mac and Windows need to be added to the QuickPerf contributing file?

Yes

>  I would add that you use the mvn -N io.takari:maven:0.7.7:wrapper command and

No

>./mvnw clean install, but with more details to the QuickPerf contributing file

Yes

**Comment by rdm100** [comment]
I have submitted a pull request let me know if that is what you are looking for.

I updated the contributing file with more information about Maven wrappers. Were you looking for more detail than that, if so where would I get more information on Maven wrappers to add to it?

**Comment by jeanbisutti** [comment]
Thanks @rdm100. I created a [PR](https://github.com/rdm100/quickperf/pulls) on your repository to propose some improvements. What do you think ? Do you notice other things to improve?
I don't think that it is needed to have too many details on Maven wrapper mechanics.

**Comment by rdm100** [comment]
@jeanbisutti I have updated CONTRIBUTING and submitted another pull request let me know if it's ok. I'm unsure of any other changes as I've never used QuickPerf or Maven Wrappers, I've used Maven though. Sorry I'm a newb to them. I'm trying to get some open source experience so am trying to get involved in any way I can:)

**Comment by jeanbisutti** [comment]
@rdm100 You close this [PR](https://github.com/rdm100/quickperf/pull/1). If you agree with the changes please reopen it and merge it. If you don't agree please explain why.

**Comment by rdm100** [comment]
@jeanbisutti ah I hadn't seen your improvements proposal! I reopened the pull request, I agree with the changes and merged them. Thanks for your patience.

**Comment by jeanbisutti** [comment]
@rdm100 
There is a merge conflict:  `<<<<<<< HEAD`
The most simple would be to refork, modidy the contributring file (perhaps by taking [this content](https://github.com/jeanbisutti/quickperf/blob/CONTRIBUTING/CONTRIBUTING.md) in my repository) and submit a new PR.

**Comment by rdm100** [comment]
@jeanbisutti do you mean refork from your original repository https://github.com/jeanbisutti/quickperf

**Comment by jeanbisutti** [comment]
@rdm100 From https://github.com/quick-perf/quickperf

**Comment by rdm100** [comment]
@jeanbisutti 
> @rdm100
> There is a merge conflict: `<<<<<<< HEAD`
> The most simple would be to refork, modidy the contributring file (perhaps by taking [this content](https://github.com/jeanbisutti/quickperf/blob/CONTRIBUTING/CONTRIBUTING.md) in my repository) and submit a new PR.

I did the above like you said I think, let me know if that's correct :)

**Comment by jeanbisutti** [comment]
@rdm100 It remains conflicts. 

The most simple would be to refork, modify the contributring file (*perhaps by replacing all the content by  [this content ](https://github.com/jeanbisutti/quickperf/blob/CONTRIBUTING/CONTRIBUTING.md)* coming from my repository) and submit a new PR.

The commit message could be: `Update contributing with Maven wrappers`

Thanks for the efforts you do for your first contribution.

**Comment by rdm100** [comment]
@jeanbisutti is there much point in modifying the file if if I just copy and paste the same content back in? Is there anything else that needs done that is suitable for a newb like me?

**Comment by jeanbisutti** [comment]
@rdm100 The merge was done with conflicts. If you do an new commit then we will have several commits for this PR. To have a clean Git history,  I would prefer to have only one commit for this PR.
So, the most simple would be to refork, modify the contributring file (*perhaps by replacing all the content by  [this content ](https://github.com/jeanbisutti/quickperf/blob/CONTRIBUTING/CONTRIBUTING.md)* coming from my repository) and submit a new PR. The commit message could be: `Update contributing with Maven wrappers`

**Comment by rdm100** [comment]
@jeanbisutti I have done what you said I think and have submitted another pull request, hopefully this 1 is correct and I haven't done something stupid, it does say there are no merge conflicts at the moment.

**Comment by jeanbisutti** [comment]
It's all good @rdm100.
Thanks.
Congratulations for your first contribution @rdm100!

**Comment by jeanbisutti** [comment]
Closed by #50

**Comment by rdm100** [comment]
@jeanbisutti haha yay, I know it was only a small thing but cool to get involved. I think it said on one of the twitter feeds for one of your contributors that you were looking for underrepresented groups to contribute, I'm in one of those groups as I am quadriplegic from a spinal injury, so that should count towards that for you

Are there any other things needing down that are not too hard? I am a computer science graduate so I do know things.
